---
- name: Update Ubuntu servers
  hosts: all
  become: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  
      
    - name: Update all packages
      apt:
        upgrade: dist
        force_apt_get: yes
      register: update_status
      
    - name: Show update status
      debug:
        msg: "{{ update_status.stdout_lines }}"